// Published case studies. Iterated by src/case-studies.njk.
//
// Field shape:
//   slug          string         filename slug under src/case-studies/
//   client        string         name as it appears on the case study card
//   liveUrl       string         live URL on the open web (or null if private)
//   screenshot    string         path under /assets/img/samples/ used as the
//                                card hero shot. Generated by
//                                scripts/capture-live-builds.mjs.
//   trade         string         what the project is, in plain language
//   metro         string         metro / city / "Open-web project" for non-local
//   summary       string         one-paragraph card description
//   metrics       array<object>  [{ label, value, note }] — surfaced on the
//                                /case-studies/ index card and the case-study page
//   tags          array<string>  filter chips (future)
//   selfStudy     bool           true for self-built projects (own brand, own audience)
//   greenfield    bool           true if no prior site existed (first build, no migration)

export default [
  {
    slug: "service-site-standard-applied-to-itself",
    client: "Pikes Peak Web Designs",
    liveUrl: "https://pikespeakwebdesigns.com",
    screenshot: null, // self-reference, no need for a screenshot card
    trade: "Custom-coded web design",
    metro: "Colorado Springs, CO (national reach)",
    summary: "The agency's own website. First site, built from scratch on the Service Site Standard. No prior site to migrate, no legacy to undo — every number on this page is what shipped on day one.",
    metrics: [
      { label: "Mobile PageSpeed", value: "95–100" },
      { label: "Core Web Vitals", value: "Green band" },
      { label: "Accessibility floor", value: "WCAG 2.2 AA" },
      { label: "Pages on launch", value: "100+" },
      { label: "Cookie banner required", value: "No" },
    ],
    tags: ["self-study", "greenfield", "custom-coded", "static-site"],
    anonymous: false,
    selfStudy: true,
    greenfield: true,
  },
  {
    slug: "the-great-agnostic",
    client: "The Great Agnostic",
    liveUrl: "https://thegreatagnostic.com",
    screenshot: "/assets/img/samples/live-great-agnostic.png",
    trade: "Literary archive",
    metro: "Open-web project",
    summary: "A complete archive of Robert Green Ingersoll's twelve-volume Dresden Edition, designed and built from a blank file. Custom Victorian typographic system, structured data per work, 177 verbatim works on a single static stack.",
    metrics: [
      { label: "Verbatim works", value: "177" },
      { label: "Mobile PageSpeed", value: "95–100" },
      { label: "Schema coverage", value: "Per-work" },
    ],
    tags: ["self-study", "greenfield", "literary", "long-form"],
    selfStudy: true,
    greenfield: true,
  },
  {
    slug: "project-broadsheet",
    client: "Project Broadsheet",
    liveUrl: "https://projectbroadsheet.com",
    screenshot: "/assets/img/samples/live-project-broadsheet.png",
    trade: "Editorial framework",
    metro: "Open-web project",
    summary: "An open-source editorial framework on Eleventy for long-form publishers. Nine editorial sections, a reviews stack, a public-domain library, full search and SEO surface, designed and built from scratch.",
    metrics: [
      { label: "Editorial sections", value: "9" },
      { label: "Mobile PageSpeed", value: "95–100" },
      { label: "Search", value: "Pagefind" },
    ],
    tags: ["self-study", "greenfield", "editorial", "open-source"],
    selfStudy: true,
    greenfield: true,
  },
  {
    slug: "the-freethinking-times",
    client: "The Freethinking Times",
    liveUrl: "https://thefreethinkingtimes.com",
    screenshot: "/assets/img/samples/live-freethinking-times.png",
    trade: "Independent publication",
    metro: "Open-web project",
    summary: "An independent publication on philosophy, history, and ideas, designed and built from a blank file. Custom editorial layout, integrated newsletter, RSS feed, no third-party trackers.",
    metrics: [
      { label: "Mobile PageSpeed", value: "95–100" },
      { label: "Newsletter", value: "Self-hosted" },
      { label: "Cookie banner", value: "No" },
    ],
    tags: ["self-study", "greenfield", "publication", "long-form"],
    selfStudy: true,
    greenfield: true,
  },
  {
    slug: "titans-of-history",
    client: "Titans of History",
    liveUrl: "https://titansofhistory.com",
    screenshot: "/assets/img/samples/live-titans-of-history.png",
    trade: "Historical reference",
    metro: "Open-web project",
    summary: "A reference site profiling the figures who shaped the modern world. Biographical depth, structured data on every entry, custom megamenu, and the same engineering posture that runs every client site here.",
    metrics: [
      { label: "Mobile PageSpeed", value: "95–100" },
      { label: "Schema coverage", value: "Per-figure" },
      { label: "Megamenu", value: "Indexable" },
    ],
    tags: ["self-study", "greenfield", "reference"],
    selfStudy: true,
    greenfield: true,
  },
];
