// All 46 FAQs that appear on /faq/. Drives the FAQPage JSON-LD output
// (via structured-data.njk) so every visible question is also a structured
// answer Google can render directly in search.
//
// Keep the visible /faq/ page in sync when you add/remove questions here.
// Answer copy is plain text (no HTML); strip inline anchors when porting.

export default [
  // Pricing & billing
  { q: "Is there really no design deposit?", a: "Yes, really. Traditional agencies charge somewhere between three and five thousand dollars up front, and I charge nothing. Your first $175 payment is what kicks off the build, and that is the entire intake fee." },
  { q: "What does the $175/month actually cover?", a: "The flat monthly rate covers custom design, the custom-coded build of up to ten pages, hosting, SSL, unlimited content updates, direct support from me, mobile-first responsive design, the on-page and local SEO foundation, and ongoing security monitoring. All of that comes in for one price." },
  { q: "Why a 12-month minimum on the monthly plan?", a: "The reason is that I do the full custom build with nothing down on your end, and the twelve-month commitment is how the math comes out even on mine. After the first year is behind you, the arrangement becomes month-to-month with thirty days of notice required to cancel." },
  { q: "What if I need to cancel early?", a: "The remaining monthly payments are due per the service agreement. I do not love early-cancel situations, so I usually find a way to work it out, but the written agreement is what governs." },
  { q: "Can I buy out the monthly plan to own the code?", a: "Yes, you can. If you decide later that you would rather own the code outright, I will quote a buyout for you. You can ask at any point in the engagement, and the conversation tends to be a straightforward one." },
  { q: "What gets billed at $100 an hour?", a: "The standard plan covers your first ten content pages, the design and build, hosting, security and maintenance, the local-SEO foundation, the blog, and unlimited content updates after launch. Anything genuinely outside that scope, such as a custom calculator, a third-party booking integration, an email-marketing template, or a data migration from an old platform, is billed at a flat one hundred dollars an hour, and I always send you a written estimate before any of it starts." },
  { q: "What if I miss a monthly payment?", a: "Cards fail sometimes, and I do not panic about it. I send a polite email letting you know the charge did not go through, and you have a fifteen-day grace window to update the card or send payment another way. Service stays online during that window. After fifteen days I check in personally before doing anything more, and the goal is always to make sure a stuck payment never quietly turns into a stuck website." },
  { q: "Are the monthly payments a business tax deduction?", a: "In almost every U.S. and Canadian small-business filing, web hosting and design fees are an ordinary business expense and fully deductible in the year they are paid. I am not a tax professional, so confirm this with your accountant, but I provide an itemized year-end receipt on request that breaks payments into categories your bookkeeper will recognize." },

  // The website
  { q: "How long does it take to build my site?", a: "Most sites are designed, built, and launched within two to three weeks of the discovery call. The timing depends mostly on how quickly you send me content from your side, namely the logo, photos, and service details." },
  { q: "How many pages do I get?", a: "The standard plan includes up to ten content pages, and any additional pages beyond that, whether additional services, additional locations, or new content pages, are billed at the flat one hundred dollars an hour rate. Most service businesses are well covered by six to eight pages, namely home, about, services, service area, FAQ, and contact." },
  { q: "Do I own my website?", a: "On the monthly plan, I own and host the code on your behalf, which is how the site can be built with nothing down on your end. The arrangement is similar to leasing a storefront, in that you get the benefit of the space without the up-front capital outlay, and if you ever decide to take the site elsewhere I will provide a clean static export that runs on any host." },
  { q: "Can I update the site myself?", a: "You do not need to update the site yourself, since unlimited updates are part of the plan. You email or text me with what you want changed, and the change tends to land quickly on most business days. If you do want a simple CMS for blogging on top of that, I can add one." },
  { q: "What about my existing site?", a: "I coordinate the launch so there is no downtime between the two sites. Once the new one is live, you can take the old one offline or archive it somewhere private, whichever you prefer." },
  { q: "Can I have a blog?", a: "Yes, you can, and the blog system is part of the standard plan rather than a separate add-on. It ships with the same setup that powers this site's blog, complete with the blog index, the post template, the sticky table of contents, the reading-progress bar, the share buttons, and an RSS feed. New posts are simply part of your unlimited content updates after the site launches." },

  // Process & support
  { q: "What's the discovery call like?", a: "The discovery call runs about twenty to thirty minutes on Google Meet, or on the phone if you prefer. On the call I learn about your business, your customers, and your goals for the site, and I answer any questions you bring along. If I turn out to be the right fit for what you need, I send a simple service agreement over and we get started." },
  { q: "Who am I actually working with?", a: "You are working with Jon Ajinga, the founder, based in Colorado Springs. There are no account managers in between us, no offshore developers picking up the work, and no handoffs as the project moves through phases. The person writing your code is the same person you email, every time." },
  { q: "What if I don't have a logo or photos?", a: "There is no problem on either count. I can design a simple logo for you starting at $300, or help you find a local photographer in your area to do a quick shoot. I can also work with whatever you already have on hand and fill in any gaps with carefully chosen stock imagery." },
  { q: "How fast is support?", a: "Routine content updates tend to land quickly on most business days. Emergencies, meaning the site being down, wrong information being live, or an urgent correction, jump the queue and get handled fast. Email, phone, or text all reach me directly, and I am available for quick turnarounds on most business days." },
  { q: "Do you work with businesses outside Colorado?", a: "Yes, I work with small businesses everywhere in the U.S. and Canada. The work runs fully remote, and the distance between us never changes the quality, the cadence, or the price." },

  // SEO & performance
  { q: "Do you guarantee Google rankings?", a: "Nobody can guarantee specific Google rankings, and if anyone tries to, you should be skeptical of the rest of what they tell you. What I do guarantee is a fast, accessible, well-structured site with clean on-page SEO, local-business schema, proper sitemaps, and strong Core Web Vitals. That is the foundation, and the rankings themselves come from that foundation along with time, content, and reviews." },
  { q: "What PageSpeed score should I expect?", a: "Every site I build runs at 95 to 100 on Google PageSpeed Insights, both mobile and desktop, with every Core Web Vital sitting comfortably in the green band." },
  { q: "Will my site be accessible?", a: "Yes. I build to WCAG 2.2 AA as the baseline, with real contrast, real focus states, and real keyboard navigation. None of it is a plugin we switch on after the fact." },
  { q: "Will I get Google Analytics?", a: "I set up privacy-focused analytics by default using Umami and Cloudflare Web Analytics, both of which are fast and cookie-banner-free. If you would rather use Google Analytics 4 alongside or instead of those, I can add it at no extra cost." },
  { q: "Do you set up my Google Business Profile?", a: "Yes, the Google Business Profile setup or audit is part of launch on every site I build. I make sure your name, address, and phone number match what is on the site, that the right primary and secondary categories are selected, that your service areas are listed correctly, and that the business is verified. After launch I revisit the profile quarterly to keep hours, photos, and posts fresh." },
  { q: "Will you write blog posts for me, or do I?", a: "By default the blog is yours to write, since you know your trade better than I do, and the publishing workflow is simply part of your unlimited content updates. If you would rather not write, I do offer ghostwritten posts billed at the flat $100 hourly rate; an average 1,200-word post lands in two to three hours. Most clients pick a blend; they outline the post, I draft it, and they edit before it goes live." },

  // Forms & operational pages
  { q: "What forms does my site come with?", a: "At minimum, a contact form powered by Web3Forms plus a matching thank-you page that appears after submission. Beyond that, I can add industry-specific forms; emergency service requests for HVAC and plumbing, free-inspection requests for roofing, bid forms for contractors, schedule-an-inspection forms for home inspectors, and so on." },
  { q: "What are operational pages and do they count against my page limit?", a: "Operational pages are the infrastructure pages every professional site needs, namely the Privacy Policy, the Accessibility Statement, the Terms of Use, Contact, Thank-You, the Style Guide, and the Sitemap. None of these count against your ten content pages, and every build ships with all seven of them as standard. You are covered legally, ethically, and technically from the day the site goes live." },
  { q: "What technical files come with the site?", a: "robots.txt, humans.txt, sitemap.xml, security.txt, a branded 404 page, a full favicon suite for every device and browser, and Open Graph and Twitter images so your links look polished when they get shared. All of it is set up once at build time and requires no maintenance from your side." },
  { q: "How do I request a content change once the site is live?", a: "The fastest way is the content update form in your client portal, since it lands in my inbox already structured and ready to act on. You can also email me or call or text directly, and all three channels reach the same inbox." },
  { q: "What if the site is down and I need help right now?", a: "Call or text me first, and then, if you can, fill out the emergency support form with the details, including what is happening, when it started, and any error messages on the screen. Emergencies skip the queue, and I am available for quick turnarounds on most business days." },
  { q: "Can I give feedback on the design while you're building?", a: "Please do, since that is the whole point of the preview link. The design feedback form is structured so every note you have lands in one place rather than scattered across emails. There is no limit on rounds and no charge per change attached to them. I would rather get the site right than get it fast." },
  { q: "Do you pay referral fees?", a: "Yes, modestly. If you refer a business and they become a client, I credit one month of hosting to your account, or send a simple cash thank-you if you are not a current client of mine. The referral form takes about a minute to fill out." },

  // Demos & samples
  { q: "Will my site be locked into one of the demo styles?", a: "No, you are not locked into any of those styles. The six demo sites exist to show that I tune the design to each industry rather than the other way around. Your site will look like your business rather than like a template, and the demos are simply reference points for visual voice." },
  { q: "Are the demos real working sites?", a: "Yes, every link, every form, every mobile menu, and every theme toggle works exactly as it would on a paid client's site. If you submit a sample form you will get a real thank you page in response, although no submission is actually sent on the back end because the access keys are sandboxed for the demos." },
  { q: "Why are sample form intakes so detailed?", a: "Real intakes in the trades are detailed. The sample forms show what a contractor actually needs in order to triage a job, including scope, urgency, address, photos, and access. A bare name-email-message form will convert at a higher rate, while an industry-specific intake will give you a lead that is genuinely usable on the other end." },
  { q: "Can I see one of your real client builds?", a: "Once I have launched a few client sites I will add a portfolio to this site. Until then, the demos represent the standard for quality, layout, and engineering that every client receives, and the site you are reading right now is also fully representative of what I ship." },

  // Onboarding & client portal
  { q: "What does onboarding actually involve?", a: "After the discovery call I send you to the onboarding form, which runs across nine sections covering your business, your services, your customers, your brand, your current site, your Google profile, the credentials I will need, and any specific deadlines on your end. Most clients fill it out in fifteen to twenty-five minutes." },
  { q: "Do I have to use the onboarding form?", a: "No, you do not. If you would rather send me a Google Doc, a Dropbox Paper file, a Notion page, or a stack of emails, any of those work fine on my end. The form simply gives the conversation a bit of structure so I do not miss anything obvious. The outcome is the same either way." },
  { q: "What's in the client portal?", a: "The client portal is a single bookmarkable page that contains everything an existing client needs, organized by where you are in the engagement. Onboarding lives there if you are new, design feedback lives there if you are mid-build, content updates and emergency support live there once you are live, and referrals, testimonials, and resource links sit alongside all of it." },
  { q: "Is there a login? Will I have a dashboard?", a: "There is no login and no dashboard, and that is a deliberate choice on my end. Admin panels are a maintenance burden and a security target you do not actually need, and everything you would do inside one, like requesting a change, seeing your form submissions, or downloading an invoice, is one email or one form away." },

  // Domain, email, and ownership
  { q: "Who owns my domain?", a: "You do, and you always will. I do not register domains on a client's behalf, because that creates the wrong control structure on the wrong day. Your domain stays registered at your registrar in your name throughout, and I simply point its DNS at my hosting." },
  { q: "Do you handle email on my domain?", a: "I do not host email myself, but I set up the DNS records (MX, SPF, DKIM, and DMARC) for whichever provider you choose, whether Google Workspace, Microsoft 365, or simple forwarding into your existing inbox. There is no separate charge for that configuration, since it is part of launch." },
  { q: "What happens to my domain if I lose track of the renewal?", a: "I monitor WHOIS expiration directly rather than relying on the registrar's email reminders, which often get lost in spam folders. I send you reminders at sixty, thirty, and seven days before expiration so the domain never lapses unintentionally. If it does happen to lapse, most TLDs have a thirty-day redemption window during which I can help you recover it." },
  { q: "If I cancel, can I take my site elsewhere?", a: "Yes, you can take the site anywhere. I will provide a static export of the live site, in clean HTML, CSS, and JavaScript, that runs on any host with no dependencies, and your domain, your content, and your forms account all belong to you throughout. There is no exit fee attached." },

  // Privacy & data
  { q: "Will my site need a cookie banner?", a: "No, your site will not need a cookie banner. The default stack of Bunny Fonts, Cloudflare Web Analytics, and Umami is fully cookie-free and GDPR-compliant by design. I only add a cookie banner if you specifically opt into a tracker that requires one." },
  { q: "Where do form submissions go?", a: "Form submissions go straight to your business email via Web3Forms, and no copy is ever stored on my side of the wire. I never see your messages unless you forward one to me." },
  { q: "Do you sell data, share with ad networks, or use trackers?", a: "No to all three. The privacy policy covers the details, and the whole stack is built around the principle of not collecting personal data I do not need in the first place." },

  // Maintenance & the long term
  { q: "How do I know if something I'm asking for is an update vs. a new feature?", a: "Editing the pages you already have, whether text, images, hours, prices, photos, or seasonal callouts, counts as a content update and is included on the monthly plan with no extra charge. Adding a brand-new page, like an extra service page or a new location, is billed once at $150 per page. Adding new behavior, such as a calculator, a gallery, a video player, or e-commerce, is a feature, and I quote those before I start." },
  { q: "What happens during a Cloudflare outage?", a: "Most Cloudflare incidents are regional rather than global, which means visitors in other regions still see your site without any disruption. If the outage is global, your site is unreachable for the duration of the incident, and I monitor Cloudflare's status feed and post updates while it is happening." },
  { q: "What's in the Owner's Guide?", a: "The Owner's Guide runs across seventeen sections that cover everything that happens after launch, including who handles what, how to ask for changes, what counts as an emergency, how form submissions work, your domain, email setup, hosting and uptime, security, SEO, analytics, your Google Business Profile, content additions, seasonal updates, your monthly invoice, leaving the relationship if it ever comes to that, and a quick contact card." },
  { q: "How often does the site actually get updated under the hood?", a: "There is no WordPress core, no plugin layer, and no admin panel to patch on a calendar. The static site itself never needs to be patched. The pieces that do get attention on a recurring basis are the build dependencies and the security headers, which I review and refresh on a quarterly cadence, and the runtime stack on Cloudflare's side, which Cloudflare patches for me. You will never get a 'your CMS needs an urgent security update' email, because there is no CMS to update." },
  { q: "What if my business name or branding changes?", a: "Rebrands happen, and the site can absorb one without a rebuild. A name and logo swap with new typography and colors is a one-day sweep included in your unlimited content updates if you are on the monthly plan. A full redesign with a different layout and new page architecture is a separate engagement that I quote like a fresh build. Either way, redirects from the old name to the new one go in on launch day so search rankings come along for the ride." },
];
