export default {
  primary: [
    { label: "How It Works", url: "/how-it-works/" },
    { label: "What's Included", url: "/whats-included/" },
    { label: "Samples", url: "/samples/" },
    { label: "Pricing", url: "/pricing/" },
    { label: "Blog", url: "/blog/" },
    { label: "About", url: "/about/" },
  ],
  megaMenu: {
    southwest: {
      label: "Southwest & West",
      cities: [
        { label: "Phoenix, AZ", slug: "phoenix-az" },
        { label: "Las Vegas, NV", slug: "las-vegas-nv" },
        { label: "Denver, CO", slug: "denver-co" },
        { label: "Los Angeles, CA", slug: "los-angeles-ca" },
        { label: "Seattle, WA", slug: "seattle-wa" },
        { label: "Salt Lake City, UT", slug: "salt-lake-city-ut" },
        { label: "San Diego, CA", slug: "san-diego-ca" },
        { label: "Portland, OR", slug: "portland-or" },
      ],
    },
    south: {
      label: "South & Texas",
      cities: [
        { label: "Houston, TX", slug: "houston-tx" },
        { label: "Dallas, TX", slug: "dallas-tx" },
        { label: "San Antonio, TX", slug: "san-antonio-tx" },
        { label: "Austin, TX", slug: "austin-tx" },
        { label: "Nashville, TN", slug: "nashville-tn" },
        { label: "Atlanta, GA", slug: "atlanta-ga" },
        { label: "Charlotte, NC", slug: "charlotte-nc" },
        { label: "Raleigh, NC", slug: "raleigh-nc" },
      ],
    },
    east: {
      label: "Florida, Midwest & Northeast",
      cities: [
        { label: "Tampa, FL", slug: "tampa-fl" },
        { label: "Miami, FL", slug: "miami-fl" },
        { label: "Jacksonville, FL", slug: "jacksonville-fl" },
        { label: "Chicago, IL", slug: "chicago-il" },
        { label: "Indianapolis, IN", slug: "indianapolis-in" },
        { label: "Columbus, OH", slug: "columbus-oh" },
        { label: "Philadelphia, PA", slug: "philadelphia-pa" },
        { label: "Baltimore, MD", slug: "baltimore-md" },
      ],
    },
    canada: {
      label: "Canada",
      cities: [
        { label: "Toronto, ON", slug: "toronto-on" },
        { label: "Vancouver, BC", slug: "vancouver-bc" },
        { label: "Calgary, AB", slug: "calgary-ab" },
        { label: "Montreal, QC", slug: "montreal-qc" },
        { label: "Edmonton, AB", slug: "edmonton-ab" },
        { label: "Ottawa, ON", slug: "ottawa-on" },
      ],
    },
  },
  mobileHighlights: [
    { label: "Phoenix, AZ", slug: "phoenix-az" },
    { label: "Houston, TX", slug: "houston-tx" },
    { label: "Dallas, TX", slug: "dallas-tx" },
    { label: "Atlanta, GA", slug: "atlanta-ga" },
    { label: "Denver, CO", slug: "denver-co" },
    { label: "Las Vegas, NV", slug: "las-vegas-nv" },
    { label: "Nashville, TN", slug: "nashville-tn" },
    { label: "Charlotte, NC", slug: "charlotte-nc" },
    { label: "Tampa, FL", slug: "tampa-fl" },
    { label: "Miami, FL", slug: "miami-fl" },
    { label: "Chicago, IL", slug: "chicago-il" },
    { label: "Los Angeles, CA", slug: "los-angeles-ca" },
    { label: "Seattle, WA", slug: "seattle-wa" },
    { label: "San Antonio, TX", slug: "san-antonio-tx" },
    { label: "Philadelphia, PA", slug: "philadelphia-pa" },
    { label: "Toronto, ON", slug: "toronto-on", canada: true },
    { label: "Vancouver, BC", slug: "vancouver-bc", canada: true },
    { label: "Calgary, AB", slug: "calgary-ab", canada: true },
    { label: "Montreal, QC", slug: "montreal-qc", canada: true },
  ],
};
