export default {
  name: "Pikes Peak Web Designs",
  shortName: "Pikes Peak",
  tagline: "A website you never have to worry about.",
  url: "https://pikespeakwebdesigns.com",
  description: "Custom-coded websites for small service businesses across the U.S. and Canada. We handle the design, the hosting, the updates, and everything else. $0 down, $175/month flat.",
  phone: "9283159094",
  phoneDisplay: "(928) 315-9094",
  email: "hello@pikespeakwebdesigns.com",
  founderSite: "https://jonajinga.com",
  meetingTool: "Google Meet",
  hours: "Mon–Fri, 8am–6pm MT · Weekend response within one business day",
  responseTime: "one business day",
  ogImage: "/assets/img/og-default.jpg",
  address: {
    city: "Colorado Springs",
    state: "CO",
    country: "US",
  },
  pricing: {
    monthly: 175,
    lumpSum: 4000,
    extraPage: 150,
    blogAddon: 200,
    minTerm: 12,
    deposit: 0,
    pagesIncluded: 10,
  },
  utilityPages: [
    "Privacy Policy",
    "Accessibility Statement",
    "Terms of Use",
    "Contact page with Web3Forms",
    "Thank-You page (form submission redirect)",
    "Testimonials page",
    "Style Guide (your brand system, documented)",
    "Sitemap (HTML + XML)",
  ],
  standardFeatures: [
    "Light and dark mode with system-preference detection",
    "Responsive header and navigation",
    "Mobile hamburger panel with accessible controls",
    "Mobile-first design from 320px up to 4K",
    "Keyboard navigation throughout",
    "Skip-to-content link for screen-reader users",
    "Built-in site search (Pagefind)",
    "Privacy-focused analytics (Umami + Cloudflare)",
  ],
  stats: {
    loadTime: "<1s",
    pageSpeed: "95–100",
    areasServed: "50 states + Canada",
    buildTime: "2–3 weeks",
  },
};
